# Generated by Django 6.0.6 on 2026-06-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BandTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactorSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("source", models.TextField(blank=True)),
                ("licence", models.CharField(blank=True, max_length=200)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("region", models.CharField(default="GB", max_length=10)),
            ],
            options={
                "ordering": ["valid_from", "name"],
            },
        ),
        migrations.CreateModel(
            name="Slice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "entry_mode",
                    models.CharField(
                        choices=[
                            ("periodic", "Periodic"),
                            ("event", "Event"),
                            ("annual_estimate", "Annual estimate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                ("help_text", models.TextField(blank=True)),
                ("group", models.CharField(blank=True, max_length=100, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "slice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="catalogue.slice",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "key"],
                "unique_together": {("slice", "key")},
            },
        ),
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_bound", models.DecimalField(decimal_places=4, max_digits=14)),
                ("value", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "band_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="catalogue.bandtable",
                    ),
                ),
            ],
            options={
                "ordering": ["lower_bound"],
                "unique_together": {("band_table", "lower_bound")},
            },
        ),
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=6, max_digits=14)),
                ("unit", models.CharField(blank=True, max_length=100)),
                ("citation", models.TextField(blank=True)),
                (
                    "factor_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factors",
                        to="catalogue.factorset",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "unique_together": {("factor_set", "key")},
            },
        ),
        migrations.CreateModel(
            name="InputField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("decimal", "Decimal"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("choices", models.JSONField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_fields",
                        to="catalogue.lineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "unique_together": {("line_item", "name")},
            },
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expression", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("test_cases", models.JSONField(default=list)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="catalogue.lineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "unique_together": {("line_item", "version")},
            },
        ),
    ]
