# Generated by Django 6.0.6 on 2026-06-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0002_evententry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicentry",
            name="formula_version",
            field=models.CharField(max_length=500),
        ),
    ]
