# Generated by Django 6.0.6 on 2026-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0004_annual_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualestimate",
            name="is_estimate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evententry",
            name="is_estimate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodicentry",
            name="is_estimate",
            field=models.BooleanField(default=False),
        ),
    ]
